### ISSUE TITLE
Unmet peerDependency when using Ractive 0.8

### ISSUE THREAD

**Issue by neersighted** [blackgate/ractive-componentify#3]
When I attempt to depend on `github:ractivejs/ractive#edge` I get this error in npm install:

```
├── UNMET PEER DEPENDENCY ractive@0.8.0-edge (git://github.com/ractivejs/ractive.git#131a942a5a75e1b9e3589f58f2348fb03606d262)
├─┬ ractive-componentify@0.2.3
│ ├── es6-promise@2.3.0
│ └── vlq@0.2.1
```

Something in the newly introduced `peerDependency` breaks on Ractive 0.8, it seems.

**Comment by blackgate** [comment]
This is now fixed on 0.2.4.
