### ISSUE TITLE
Update to use 0.8

### ISSUE THREAD

**Issue by briancray** [blackgate/ractive-componentify#4]
0.8 has been released. Right now if I try to use ractive-componentify with 0.8 it says it "Error: Parsing file /foo/bar.ract: Unexpected token. Works when using Ractive 0.7.x with ractive-componentify

**Comment by blackgate** [comment]
Sorry for not replying sooner, but I have been a bit busy lately. Anyway, I have tested and it should work with the latest version 0.8.1.

**Comment by briancray** [comment]
I think I see the problem. You likely didn't run into the problem because you're testing with plain JS and plain CSS components.

Here's the problem: In compileToCSS and compileToJS the source.type is always undefined.

https://github.com/blackgate/ractive-componentify/blob/master/lib/build.js#L103

After diving deeper I found that extractFragment is looking in the wrong place for type. Maybe Ractive changed the location

https://github.com/blackgate/ractive-componentify/blob/master/lib/transform.js#L81

The new location appears to be something like m[0].f

`"m":[{"n":"type","f":"text/sass","t":13}]`

**Comment by briancray** [comment]
Or perhaps you have to iterate over `m` until `n === "type"` then get `f` key. It just so happens that my `type` attribute is the first and only attribute.

**Comment by blackgate** [comment]
This is now fixed on 0.2.5.
